package pruebas;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import es.uma.informatica.sii.anotaciones.Requisitos;

public class TrazabilidadIT {
	private static final String UNIDAD_PERSISTENCIA_PRUEBAS = "TrazabilidadIT";
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	private static String baseURL;
	private static Map<String,String> propiedadesExtra = new HashMap<>();

	@BeforeClass
	public static void setupClass() {
		String server="localhost";
		try (InputStream is = TrazabilidadIT.class.getClassLoader().getResourceAsStream("pom.properties")) {
			Properties pomProperties = new Properties();
			pomProperties.load(is);
			server=pomProperties.getProperty("server.host");
			String databaseURL = "jdbc:mysql://"+server+":3306/sii";
			propiedadesExtra.put("javax.persistence.jdbc.url", databaseURL);
		} catch (IOException e) {
			e.printStackTrace();
		}
		baseURL="http://"+server+":8080/trazabilidad-war/";
	}

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		BaseDatos.inicializaBaseDatos(UNIDAD_PERSISTENCIA_PRUEBAS, propiedadesExtra);
	}
	@After
	public void tearDown() {
		driver.quit();
	}
	
	@SuppressWarnings("deprecation")
	@Requisitos({"RF1"})
	@Test
	public void inicioAdmin() {
		driver.get(baseURL+"admin.xhtml");
		driver.findElement(By.id("entradaUserApk:user")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:pass")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:btnLogin")).click();
		assertThat(driver.findElement(By.id("userLabel")).getText(), is("ponciano"));
		driver.close();
	}
	
	@SuppressWarnings("deprecation")
	@Requisitos({"RF2"})
	@Test
	public void altaCliente() {
		driver.get(baseURL+"admin.xhtml");
		driver.findElement(By.id("entradaUserApk:user")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:pass")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:btnLogin")).click();
		driver.findElement(By.id("listaClientes")).click();
		driver.findElement(By.id("empresas:nuevaEmpresa")).click();
		driver.findElement(By.id("entradaEmpresa:razon")).sendKeys("RazonSocial 1234");
		driver.findElement(By.id("entradaEmpresa:ident")).sendKeys("131243244D");
		driver.findElement(By.id("entradaEmpresa:direccion")).sendKeys("Calle Sostola 123");
		driver.findElement(By.id("entradaEmpresa:ciudad")).sendKeys("Malaga");
		driver.findElement(By.id("entradaEmpresa:cp")).sendKeys("29007");
		driver.findElement(By.id("entradaEmpresa:pais")).sendKeys("Irlanda");
		driver.findElement(By.id("entradaEmpresa:btnConfirm")).click();
		assertThat(driver.findElement(By.id("clientList")).getText(), is("Lista de clientes"));
		driver.close();
	}
	
	@SuppressWarnings("deprecation")
	@Requisitos({"RF3"})
	@Test
	public void editarCliente() {
		driver.get(baseURL+"admin.xhtml");
		driver.findElement(By.id("entradaUserApk:user")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:pass")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:btnLogin")).click();
		driver.findElement(By.id("listaClientes")).click();
		driver.findElement(By.id("empresas:editarEmpresa")).click();
		driver.findElement(By.id("entradaEmpresa:razon")).sendKeys("RazonSocial 2341");
		driver.findElement(By.id("entradaEmpresa:btnConfirm")).click();
		assertThat(driver.findElement(By.id("clientList")).getText(), is("Lista de clientes"));
		driver.close();
	}
	
	@SuppressWarnings("deprecation")
	@Requisitos({"RF4"})
	@Test
	public void bajaCliente() {
		driver.get(baseURL+"admin.xhtml");
		driver.findElement(By.id("entradaUserApk:user")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:pass")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:btnLogin")).click();
		driver.findElement(By.id("listaClientes")).click();
		driver.findElement(By.id("empresas:buttonBajaEmpresa")).click();
		assertThat(driver.findElement(By.id("clientList")).getText(), is("Lista de clientes"));
		driver.close();
	}
	
	@SuppressWarnings("deprecation")
	@Requisitos({"RF5"})
	@Test
	public void altaCuenta() {
		driver.get(baseURL+"admin.xhtml");
		driver.findElement(By.id("entradaUserApk:user")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:pass")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:btnLogin")).click();
		driver.findElement(By.id("listaCuentas")).click();
		driver.findElement(By.id("pooled:nueva")).click();
		driver.findElement(By.id("crearPooled:IBAN")).sendKeys("ES23523345235235");
		driver.findElement(By.id("crearPooled:SWIFT")).sendKeys("Swift");
		driver.findElement(By.id("crearPooled:euros")).sendKeys("2000");
		driver.findElement(By.id("crearPooled:btnConfirm")).click();
		assertThat(driver.findElement(By.id("accountList")).getText(), is("Lista de cuentas"));
		driver.close();
	}
	
	@SuppressWarnings("deprecation")
	@Requisitos({"RF6"})
	@Test
	public void addAutorizado() {
		driver.get(baseURL+"admin.xhtml");
		driver.findElement(By.id("entradaUserApk:user")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:pass")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:btnLogin")).click();
		driver.findElement(By.id("listaAutorizados")).click();
		driver.findElement(By.id("autorizados:nuevo")).click();
		driver.findElement(By.id("entradaAutoriz:nombre")).sendKeys("Ismael");
		driver.findElement(By.id("entradaAutoriz:apellidos")).sendKeys("Apellido");
		driver.findElement(By.id("entradaAutoriz:ident")).sendKeys("23423");
		driver.findElement(By.id("entradaAutoriz:direccion")).sendKeys("Calle error 404");
		driver.findElement(By.id("entradaAutoriz:btnConfirm")).click();
		assertThat(driver.findElement(By.id("autorizList")).getText(), is("Lista de Autorizados"));
		driver.close();
	}
	
	@SuppressWarnings("deprecation")
	@Requisitos({"RF7"})
	@Test
	public void editarAutorizado() {
		driver.get(baseURL+"admin.xhtml");
		driver.findElement(By.id("entradaUserApk:user")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:pass")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:btnLogin")).click();
		driver.findElement(By.id("listaAutorizados")).click();
		driver.findElement(By.id("autorizados:editar")).click();
		driver.findElement(By.id("entradaAutoriz:apellidos")).sendKeys("");
		driver.findElement(By.id("entradaAutoriz:apellidos")).sendKeys("Gutiérrez");
		driver.findElement(By.id("entradaAutoriz:btnConfirm")).click();
		assertThat(driver.findElement(By.id("autorizList")).getText(), is("Lista de Autorizados"));
		driver.close();
	}
	
	@SuppressWarnings("deprecation")
	@Requisitos({"RF8"})
	@Test
	public void bajaAutorizado() {
		driver.get(baseURL+"admin.xhtml");
		driver.findElement(By.id("entradaUserApk:user")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:pass")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:btnLogin")).click();
		driver.findElement(By.id("listaAutorizados")).click();
		driver.findElement(By.id("autorizados:baja")).click();
		driver.findElement(By.id("entradaBajaAutoriz:btnConfirm")).click();
		assertThat(driver.findElement(By.id("autorizList")).getText(), is("Lista de Autorizados"));
		driver.close();
	}
	
	@SuppressWarnings("deprecation")
	@Requisitos({"RF9"})
	@Test
	public void cierreCuenta() {
		driver.get(baseURL+"admin.xhtml");
		driver.findElement(By.id("entradaUserApk:user")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:pass")).sendKeys("ponciano");
		driver.findElement(By.id("entradaUserApk:btnLogin")).click();
		driver.findElement(By.id("listaCuentas")).click();
		driver.findElement(By.id("pooled:buttonBaja")).click();
		assertThat(driver.findElement(By.id("accountList")).getText(), is("Lista de cuentas"));
		driver.close();
	}
	
	@SuppressWarnings("deprecation")
	@Requisitos({"RF10"})
	@Test
	public void inicioAutorizado() {
		driver.get(baseURL+"index.xhtml");
		driver.findElement(By.id("entradaUserApk:user")).sendKeys("ana");
		driver.findElement(By.id("entradaUserApk:pass")).sendKeys("ana");
		driver.findElement(By.id("entradaUserApk:btnLogin")).click();
		assertThat(driver.findElement(By.id("userLabel")).getText(), is("ana"));
		driver.close();
	}
}
